In [2]:
from bs4 import BeautifulSoup
import requests
import numpy as np
import pandas as pd

movie_name = [] 
year = []
time = []
rating = []
metascore = []
votes = []
gross = []

In [3]:
url = "https://www.imdb.com/search/title/?count=100&groups=top_1000&sort=user_rating"
r = requests.get(url)
soup = BeautifulSoup(r.content, "html.parser")

movie_name = [] 
year = [] 
time = [] 
rating = [] 
metascore = [] 
votes = [] 
gross = []

movie_data = soup.find_all("div", class_ = "lister-item mode-advanced")


for i in movie_data:
    name = i.h3.a.text
    movie_name.append(name)
#     print(name)
    
    years = i.h3.find("span", class_="lister-item-year text-muted unbold").text.replace("(", " ").replace(")", " ")
    year.append(years)
#     print(years)
    
    run_time = i.p.find("span", class_="runtime").text
    time.append(run_time)
#     print(run_time)
    
    ratings = i.find("div", class_="inline-block ratings-imdb-rating").text.replace("\n", "")
    rating.append(ratings)
#     print(ratings)

    metascores = i.find("div", class_="inline-block ratings-metascore").text.replace("Metascore", "").replace("\n", "") if i.find("span", class_="metascore") else "None" 
    metascore.append(metascores)
#     print(metascores)

    votes_and_gross = i.find_all("span", attrs = {"name": "nv"})
    
    votes_ = votes_and_gross[0].text
    votes.append(votes_)
#     print(votes_)
    
    gross_ = votes_and_gross[1].text if len(votes_and_gross)>1 else "None"
    gross.append(gross_)
#     print(gross_)

In [4]:
IMDb_rated_top_100_movies = pd.DataFrame({"Movie Name": movie_name, 
                                         "Year of Release": year, 
                                         "Runtime": time, 
                                         "Ratings": rating, 
                                         "Metascore": metascore, 
                                         "Votes": votes, 
                                         "Gross": gross})
print(IMDb_rated_top_100_movies)

                               Movie Name Year of Release  Runtime Ratings  \
0                The Shawshank Redemption           1994   142 min     9.3
1                           The Godfather           1972   175 min     9.2
2                         The Dark Knight           2008   152 min     9.0
3                  The Godfather: Part II           1974   202 min     9.0
4                            12 Angry Men           1957    96 min     9.0
..                                    ...             ...      ...     ...
95  Eternal Sunshine of the Spotless Mind           2004   108 min     8.3
96                                 Am√©lie           2001   122 min     8.3
97                                 Snatch           2000   104 min     8.3
98                    Requiem for a Dream           2000   102 min     8.3
99                        American Beauty           1999   122 min     8.3

                          Metascore      Votes     Gross
0    80                              2,347,556   $28.34M
1   100                              1,623,860  $134.97M
2    84                              2,307,430  $534.86M
3    90                              1,132,216   $57.30M
4    96                                691,472    $4.36M
..                              ...        ...       ...
95   89                                913,140   $34.40M
96   69                                704,771   $33.23M
97   55                                783,231   $30.33M
98   68                                768,264    $3.64M
99   84                              1,071,303  $130.10M

[100 rows x 7 columns]

In [5]:
IMDb_rated_top_100_movies.to_csv("IMDb_rated_top_100_movies.csv")

In [7]:
IMDb_rated_top_100_movies.head()

,Movie Name,Year of Release,Runtime,Ratings,Metascore,Votes,Gross
0,The Shawshank Redemption,1994,142 min,9.3,80,"2,347,556",$28.34M
1,The Godfather,1972,175 min,9.2,100,"1,623,860",$134.97M
2,The Dark Knight,2008,152 min,9.0,84,"2,307,430",$534.86M
3,The Godfather: Part II,1974,202 min,9.0,90,"1,132,216",$57.30M
4,12 Angry Men,1957,96 min,9.0,96,"691,472",$4.36M

In [8]:
IMDb_rated_top_100_movies.tail()

,Movie Name,Year of Release,Runtime,Ratings,Metascore,Votes,Gross
95,Eternal Sunshine of the Spotless Mind,2004,108 min,8.3,89,"913,140",$34.40M
96,Am√©lie,2001,122 min,8.3,69,"704,771",$33.23M
97,Snatch,2000,104 min,8.3,55,"783,231",$30.33M
98,Requiem for a Dream,2000,102 min,8.3,68,"768,264",$3.64M
99,American Beauty,1999,122 min,8.3,84,"1,071,303",$130.10M